### PR TITLE
Fix crusher null pointer exceptions

### PR DESCRIPTION
**Pull request by hiperbou**
This fixes a bug in some Doom Wads, most notably the IWAD for Doom2 throws a null pointer exception during the crusher in MAP06, when the player walks on top of the active platform after the demons have been crushed.

This PR was supposed to fix the same problem too:
https://github.com/AXDOOMER/mochadoom/pull/20

But it it still crashed if you try to save the game afterwards, and generated a corrupted savegame.

This PR fixes both issues.

### CODE REVIEW

**Comment by AXDOOMER** [comment]
Thank you! I'll have a look.

**Comment by AXDOOMER** [comment]
Thank you for your contribution!

**Comment by hiperbou** [comment]
> Thank you for your contribution!

Also if you're interested, I forked mochadoom and translated it from Java to Kotlin. In the long term, I will try to refactor it to a Kotlin Multiplatform project, so it could run in the JVM, Javascript (browser) or native platforms. (which may seem something totally useless, but why not?)

https://github.com/hiperbou/kocoa-doom

**Comment by AXDOOMER** [comment]
Yes, I'll keep an eye open on it. Seems like a very interesting project.

**Pull request merged**
